### ISSUE TITLE
Update Read/Write Use Cases

### ISSUE THREAD

**Issue by NilsG-S** [NilsG-S/team-null-front-end#2]
These are the changes that Dr. Shin required:

- Create treatment record needs to be separated from write to treatment record. Create treatment record will only be for staff.
- Express that nurse has different write permissions than doctor.
- Make description more detailed. Be very specific about input from actor and response from system.
- Use `extend` and `include`

**Comment by dlowrey** [comment]
I did this in a new google doc _Use Cases (V2)_. I don't know how detailed I needed to get with input and response but I think it looks good.
