### ISSUE TITLE
Add System (Timer) Actor

### ISSUE THREAD

**Issue by NilsG-S** [NilsG-S/team-null-front-end#3]
Dr. Shin required that system tasks be added to the use cases as timer.

- No-shows
- Daily reports
- Monthly reports

Note: daily reports and monthly reports should be separate.

**Comment by dlowrey** [comment]
I'll add the use cases in the google doc soon. (If no one has yet)

**Comment by dlowrey** [comment]
Done. Reformatted and updated use cases in a new google doc _Use Cases (V2)_
