### ISSUE TITLE
Registration System

### ISSUE THREAD

**Issue by NilsG-S** [NilsG-S/team-null-front-end#6]
The specification says that the hospital has a CEO, 5 doctors, 5 nurses, and 3 staff members. The way it is stated suggests that there is no need for a registration system, because the users are already defined. My proposal is that we put a registration system on the very back burner because it doesn't seem to be strictly necessary.

Is this something we should talk to the professor about?

**Comment by dlowrey** [comment]
So there will be no way for new user's to register, like if a nurse quits and a new one gets hired? We should probably ask about it like you suggested.
