### ISSUE TITLE
Convert from Google Docs to Microsoft Word online

### ISSUE THREAD

**Issue by dlowrey** [NilsG-S/team-null-front-end#7]
Nils mentioned that Microsoft Word might have some better formatting options.

**Comment by dlowrey** [comment]
I have created a new _Use Case (V2)_ Google Doc and tried to format it well.

**Comment by dlowrey** [comment]
I have also included bookmarks and an index like feature at the top so different use cases are easily acessed

**Comment by NilsG-S** [comment]
Done
